### ISSUE TITLE
Invariant Violation: Module  is not a registered callable module (calling onMessage) on Android only

### ISSUE THREAD

**Issue by Janendran** [reggie3/react-native-webview-quilljs#70]
Invariant Violation: Module  is not a registered callable module (calling onMessage)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

**Comment by Janendran** [comment]
@reggie3  any solution?
